# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-25 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.AddField(
            model_name='user',
            name='sucess',
            field=models.BooleanField(default=True),
        ),
    ]
