# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.StatusPurchase'),
            preserve_default=False,
        ),
    ]
